
[app]
title = Invoice Extractor Pro
package.name = invoiceextractor
package.domain = org.example
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,ttf
version = 1.0.0
requirements = python3,kivy==2.2.1,pillow,pytesseract,opencv-python-headless,numpy,PyMuPDF
orientation = portrait
fullscreen = 0
android.permissions = INTERNET,READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE
android.api = 33
android.minapi = 21
android.sdk = 33
android.ndk = 25b
android.arch = arm64-v8a
android.gradle_dependencies = 
android.add_aars = 
android.add_jars = 
android.add_src = 
android.add_assets = 
android.add_resources = 
android.private_storage = True
android.whitelist = 
android.blacklist = 
android.presplash_color = #FFFFFF
android.presplash_lottie = 
android.wakelock = False
android.meta_data = 
android.library = 
android.logcat_filters = *:S python:D
android.copy_libs = 1
android.ant_path = 
android.sdk_path = 
android.ndk_path = 
android.java_home = 
android.accept_sdk_license = True
android.skip_update = False
android.no_sdk = False
android.entrypoint = org.kivy.android.PythonActivity
android.apptheme = @android:style/Theme.NoTitleBar
android.release_artifact = apk
android.allow_backup = True
android.backup_rules = 
android.add_compile_options = 
android.add_gradle_repositories = 
android.packaging_options = 
android.archs = arm64-v8a, armeabi-v7a
android.allow_gles_ver = 
android.add_native_code = 
android.add_assets = 
[buildozer]
log_level = 2
warn_on_root = 1
